version: "3"
volumes: 
  dbVolume:
  fortifyVolume:
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "fortify"
      MYSQL_USER: "fortify"
      MYSQL_PASSWORD: "fortify"
    volumes:
      - dbVolume:/var/lib/mysql
      - ./sql/mysql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    command: "--character-set-server=utf8 --collation-server=utf8_bin --max_allowed_packet=1G --sql_mode=TRADITIONAL"
  web:
    depends_on:
      - "db"
    image: fortify-web:latest
    ports:
      - "8080:8080"
    volumes:
      - fortifyVolume:/opt/fortify
      - ./mysql-connector-java-5.1.49.jar:/usr/local/tomcat/lib/mysql-connector-java.jar